import { Router, Request } from 'express';
import { PrismaClient } from '@prisma/client';
import { authMiddleware } from '../middleware/auth.js';
import { asyncHandler, AppError } from '../middleware/errorHandler.js';
import { dispatchWorkflowEvent, workflowEvent } from '../services/workflow.events.js';

const router = Router(); const prisma = new PrismaClient();
router.use(authMiddleware);
async function workspaceId(req: Request) { const id = req.params.workspaceId; const member = await prisma.workspaceMember.findUnique({ where: { userId_workspaceId: { userId: req.auth!.userId, workspaceId: id } } }); if (!member) throw new AppError(404, 'Workspace not found'); return id; }
async function contactInWorkspace(id: string, contactId: string) { const contact = await prisma.contact.findFirst({ where: { id: contactId, workspaceId: id, deletedAt: null } }); if (!contact) throw new AppError(400, 'Contact does not belong to this workspace'); return contact; }
async function conversationInWorkspace(id: string, conversationId: string) { const conversation = await prisma.conversation.findFirst({ where: { id: conversationId, workspaceId: id }, include: { channel: true, contact: true } }); if (!conversation) throw new AppError(404, 'Conversation not found'); return conversation; }

router.get('/workspaces/:workspaceId/channels', asyncHandler(async (req, res) => { const id = await workspaceId(req); const channels = await prisma.channel.findMany({ where: { workspaceId: id }, orderBy: { name: 'asc' } }); res.json({ success: true, data: { channels } }); }));
router.post('/workspaces/:workspaceId/channels', asyncHandler(async (req, res) => { const id = await workspaceId(req); const types = ['email', 'sms', 'whatsapp', 'internal']; if (!req.body.name || !types.includes(req.body.type)) throw new AppError(400, 'Valid channel name and type are required'); const channel = await prisma.channel.create({ data: { workspaceId: id, name: req.body.name, type: req.body.type, config: req.body.config } }); res.status(201).json({ success: true, data: { channel } }); }));

router.get('/workspaces/:workspaceId/conversations', asyncHandler(async (req, res) => {
  const id = await workspaceId(req); const where: any = { workspaceId: id };
  if (req.query.status) where.status = String(req.query.status); if (req.query.channelId) where.channelId = String(req.query.channelId); if (req.query.assigned === 'me') where.assignedUserId = req.auth!.userId; if (req.query.unread === 'true') where.participants = { some: { userId: req.auth!.userId, unreadCount: { gt: 0 } } };
  const search = String(req.query.search || '').trim(); if (search) where.OR = [{ subject: { contains: search, mode: 'insensitive' } }, { contact: { firstName: { contains: search, mode: 'insensitive' } } }, { contact: { lastName: { contains: search, mode: 'insensitive' } } }, { contact: { email: { contains: search, mode: 'insensitive' } } }];
  const conversations = await prisma.conversation.findMany({ where, orderBy: { lastMessageAt: 'desc' }, include: { channel: true, contact: true, assignedUser: { select: { id: true, firstName: true, lastName: true } }, participants: { where: { userId: req.auth!.userId } }, messages: { take: 1, orderBy: { createdAt: 'desc' } } } }); res.json({ success: true, data: { conversations } });
}));
router.post('/workspaces/:workspaceId/conversations', asyncHandler(async (req, res) => {
  const id = await workspaceId(req); const { contactId, channelId, subject, assignedUserId } = req.body; if (!contactId || !channelId) throw new AppError(400, 'Contact and channel are required'); const contact = await contactInWorkspace(id, contactId); const channel = await prisma.channel.findFirst({ where: { id: channelId, workspaceId: id, isActive: true } }); if (!channel) throw new AppError(400, 'Channel does not belong to this workspace');
  if (assignedUserId && !await prisma.workspaceMember.findUnique({ where: { userId_workspaceId: { userId: assignedUserId, workspaceId: id } } })) throw new AppError(400, 'Assignee is not a workspace member');
  const conversation = await prisma.$transaction(async tx => { const created = await tx.conversation.create({ data: { workspaceId: id, contactId: contact.id, channelId: channel.id, subject, assignedUserId } }); await tx.conversationParticipant.create({ data: { conversationId: created.id, userId: req.auth!.userId } }); if (assignedUserId && assignedUserId !== req.auth!.userId) await tx.conversationParticipant.create({ data: { conversationId: created.id, userId: assignedUserId } }); if (assignedUserId) await tx.conversationAssignment.create({ data: { conversationId: created.id, assignedToUserId: assignedUserId, assignedByUserId: req.auth!.userId } }); return created; }); res.status(201).json({ success: true, data: { conversation } });
}));
router.get('/workspaces/:workspaceId/conversations/:conversationId', asyncHandler(async (req, res) => { const id = await workspaceId(req); const conversation = await conversationInWorkspace(id, req.params.conversationId); const messages = await prisma.message.findMany({ where: { conversationId: conversation.id }, include: { attachments: true }, orderBy: { createdAt: 'asc' } }); await prisma.conversationParticipant.upsert({ where: { conversationId_userId: { conversationId: conversation.id, userId: req.auth!.userId } }, create: { conversationId: conversation.id, userId: req.auth!.userId, lastReadAt: new Date(), unreadCount: 0 }, update: { lastReadAt: new Date(), unreadCount: 0 } }); res.json({ success: true, data: { conversation, messages } }); }));
router.post('/workspaces/:workspaceId/conversations/:conversationId/messages', asyncHandler(async (req, res) => {
  const id = await workspaceId(req); const conversation = await conversationInWorkspace(id, req.params.conversationId); const { body, type = 'text', attachments = [] } = req.body; if (!body) throw new AppError(400, 'Message body is required'); if (!['text', 'internal_note'].includes(type)) throw new AppError(400, 'Unsupported message type');
  const message = await prisma.$transaction(async tx => { const created = await tx.message.create({ data: { conversationId: conversation.id, channelId: conversation.channelId, senderUserId: req.auth!.userId, direction: type === 'internal_note' ? 'internal' : 'outbound', type, body, deliveryStatus: type === 'internal_note' ? 'sent' : 'queued', attachments: { create: attachments.map((a: any) => ({ fileName: a.fileName, mimeType: a.mimeType, url: a.url, size: a.size })) } }, include: { attachments: true } }); await tx.conversation.update({ where: { id: conversation.id }, data: { lastMessageAt: new Date() } }); await tx.conversationParticipant.updateMany({ where: { conversationId: conversation.id, userId: { not: req.auth!.userId } }, data: { unreadCount: { increment: 1 } } }); await tx.contactActivity.create({ data: { workspaceId: id, contactId: conversation.contactId, type: type === 'internal_note' ? 'note' : conversation.channel.type, title: type === 'internal_note' ? 'Internal note added' : `${conversation.channel.type.toUpperCase()} message sent`, description: body } }); return created; }); res.status(201).json({ success: true, data: { message } });
}));
// Provider adapters should validate their webhook signature before invoking
// this authenticated ingress. Keeping inbound creation separate prevents an
// ordinary agent reply from accidentally firing an inbound-message workflow.
router.post('/workspaces/:workspaceId/conversations/:conversationId/messages/inbound', asyncHandler(async (req, res) => {
  const id = await workspaceId(req); const conversation = await conversationInWorkspace(id, req.params.conversationId);
  const { body, attachments = [], providerMessageId } = req.body; if (!body) throw new AppError(400, 'Message body is required');
  const message = await prisma.$transaction(async tx => {
    const created = await tx.message.create({ data: { conversationId: conversation.id, channelId: conversation.channelId, direction: 'inbound', type: 'text', body, deliveryStatus: 'delivered', attachments: { create: attachments.map((a: any) => ({ fileName: a.fileName, mimeType: a.mimeType, url: a.url, size: a.size })) } }, include: { attachments: true } });
    await tx.conversation.update({ where: { id: conversation.id }, data: { status: 'open', lastMessageAt: new Date() } });
    await tx.conversationParticipant.updateMany({ where: { conversationId: conversation.id }, data: { unreadCount: { increment: 1 } } });
    await tx.contactActivity.create({ data: { workspaceId: id, contactId: conversation.contactId, type: conversation.channel.type, title: `${conversation.channel.type.toUpperCase()} message received`, description: body } }); return created;
  });
  void dispatchWorkflowEvent(workflowEvent(id, 'incoming_message_received', { contactId: conversation.contactId, triggeredByUserId: req.auth!.userId, payload: { contactId: conversation.contactId, conversationId: conversation.id, messageId: message.id, channelId: conversation.channelId, eventId: providerMessageId || message.id }, deduplicationKey: `incoming-message:${providerMessageId || message.id}` })).catch((error) => console.error('Unable to dispatch incoming-message workflow event', error));
  res.status(201).json({ success: true, data: { message } });
}));
router.put('/workspaces/:workspaceId/conversations/:conversationId/assignment', asyncHandler(async (req, res) => { const id = await workspaceId(req); const conversation = await conversationInWorkspace(id, req.params.conversationId); const assignedUserId = req.body.assignedUserId || null; if (assignedUserId && !await prisma.workspaceMember.findUnique({ where: { userId_workspaceId: { userId: assignedUserId, workspaceId: id } } })) throw new AppError(400, 'Assignee is not a workspace member'); await prisma.$transaction([prisma.conversation.update({ where: { id: conversation.id }, data: { assignedUserId } }), prisma.conversationAssignment.create({ data: { conversationId: conversation.id, assignedToUserId: assignedUserId, assignedByUserId: req.auth!.userId } })]); res.json({ success: true }); }));
router.put('/workspaces/:workspaceId/conversations/:conversationId/status', asyncHandler(async (req, res) => { const id = await workspaceId(req); const conversation = await conversationInWorkspace(id, req.params.conversationId); if (!['open', 'closed', 'archived'].includes(req.body.status)) throw new AppError(400, 'Invalid status'); await prisma.conversation.update({ where: { id: conversation.id }, data: { status: req.body.status } }); res.json({ success: true }); }));
router.put('/workspaces/:workspaceId/conversations/:conversationId/read', asyncHandler(async (req, res) => { const id = await workspaceId(req); const conversation = await conversationInWorkspace(id, req.params.conversationId); const unreadCount = req.body.unread ? 1 : 0; await prisma.conversationParticipant.upsert({ where: { conversationId_userId: { conversationId: conversation.id, userId: req.auth!.userId } }, create: { conversationId: conversation.id, userId: req.auth!.userId, unreadCount }, update: { unreadCount, lastReadAt: req.body.unread ? undefined : new Date() } }); res.json({ success: true }); }));
export default router;
