import { FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import type { Workspace } from '../types';

type Contact = { id: string; firstName: string; lastName: string; email?: string; phone?: string; source?: string; tags: { tag: { id: string; name: string; color: string } }[] };
type Pipeline = { id: string; name: string; stages: { id: string; name: string; color: string; opportunities: { id: string; title: string; dealValue?: number; contact: { firstName: string; lastName: string } }[] }[] };
type Tag = { id: string; name: string; color: string };
type CustomField = { id: string; name: string; fieldType: string; isRequired: boolean };

export function CrmPage() {
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [workspaceId, setWorkspaceId] = useState('');
  const [tab, setTab] = useState<'dashboard' | 'contacts' | 'pipeline' | 'settings'>('dashboard');
  const [contacts, setContacts] = useState<Contact[]>([]); const [pipelines, setPipelines] = useState<Pipeline[]>([]);
  const [tags, setTags] = useState<Tag[]>([]); const [fields, setFields] = useState<CustomField[]>([]); const [search, setSearch] = useState(''); const [message, setMessage] = useState('');
  const [showContact, setShowContact] = useState(false); const [showPipeline, setShowPipeline] = useState(false);

  useEffect(() => { api.get('/workspaces').then(r => { const list = r.data.data.workspaces as Workspace[]; setWorkspaces(list); setWorkspaceId(list[0]?.id || ''); }).catch(() => setMessage('Unable to load workspaces.')); }, []);
  useEffect(() => { if (workspaceId) void load(); }, [workspaceId, search]);
  async function load() { try { const base = `/crm/workspaces/${workspaceId}`; const [c, p, t, f] = await Promise.all([api.get(`${base}/contacts?search=${encodeURIComponent(search)}`), api.get(`${base}/pipelines`), api.get(`${base}/tags`), api.get(`${base}/custom-fields`)]); setContacts(c.data.data.contacts); setPipelines(p.data.data.pipelines); setTags(t.data.data.tags); setFields(f.data.data.customFields); } catch { setMessage('Unable to load CRM data.'); } }
  async function createContact(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); try { await api.post(`/crm/workspaces/${workspaceId}/contacts`, { firstName: form.get('firstName'), lastName: form.get('lastName'), email: form.get('email'), phone: form.get('phone'), source: form.get('source'), tagIds: form.getAll('tagIds') }); setShowContact(false); setMessage('Contact created.'); void load(); } catch (err: any) { setMessage(err.response?.data?.error || 'Could not create contact.'); } }
  async function createPipeline(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); try { await api.post(`/crm/workspaces/${workspaceId}/pipelines`, { name: form.get('name'), description: form.get('description') }); setShowPipeline(false); setMessage('Pipeline created with default stages.'); void load(); } catch { setMessage('Could not create pipeline.'); } }
  async function moveOpportunity(opportunityId: string, stageId: string) { try { await api.put(`/crm/workspaces/${workspaceId}/opportunities/${opportunityId}`, { stageId }); void load(); } catch { setMessage('Could not move opportunity.'); } }
  async function addTag(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); await api.post(`/crm/workspaces/${workspaceId}/tags`, { name: form.get('name'), color: form.get('color') || '#3B82F6' }); e.currentTarget.reset(); void load(); }
  async function addField(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); await api.post(`/crm/workspaces/${workspaceId}/custom-fields`, { name: form.get('name'), fieldType: form.get('fieldType'), isRequired: form.get('isRequired') === 'on' }); e.currentTarget.reset(); void load(); }
  if (!workspaces.length) return <main className="p-8"><h1 className="text-2xl font-bold">CRM</h1><p className="mt-3">Create a workspace first, then return here to manage its contacts and sales pipeline.</p><Link className="text-blue-600" to="/organizations">Go to organizations</Link></main>;
  const base = 'rounded-lg border bg-white p-5 shadow-sm';
  return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Link to="/dashboard" className="text-sm text-blue-600">← Dashboard</Link><h1 className="text-3xl font-bold text-slate-900">CRM</h1></div><select value={workspaceId} onChange={e => setWorkspaceId(e.target.value)} className="rounded border p-2">{workspaces.map(w => <option key={w.id} value={w.id}>{w.name}</option>)}</select></div>
    <nav className="mb-6 flex gap-2 overflow-auto">{(['dashboard', 'contacts', 'pipeline', 'settings'] as const).map(item => <button key={item} onClick={() => setTab(item)} className={`rounded px-4 py-2 capitalize ${tab === item ? 'bg-blue-600 text-white' : 'bg-white text-slate-700'}`}>{item}</button>)}</nav>{message && <p className="mb-4 rounded bg-blue-50 p-3 text-blue-800">{message}</p>}
    {tab === 'dashboard' && <section className="grid gap-4 md:grid-cols-3"><div className={base}><p className="text-slate-500">Contacts</p><p className="text-3xl font-bold">{contacts.length}</p></div><div className={base}><p className="text-slate-500">Pipelines</p><p className="text-3xl font-bold">{pipelines.length}</p></div><div className={base}><p className="text-slate-500">Open deals</p><p className="text-3xl font-bold">{pipelines.reduce((n, p) => n + p.stages.reduce((s, st) => s + st.opportunities.length, 0), 0)}</p></div><div className={`${base} md:col-span-3`}><h2 className="font-semibold">Workspace CRM</h2><p className="mt-2 text-slate-600">Use Contacts to manage people and their timeline; use Pipeline for a drag-and-drop deal board.</p></div></section>}
    {tab === 'contacts' && <section><div className="mb-4 flex flex-wrap gap-3"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search contacts" className="rounded border p-2"/><button onClick={() => setShowContact(true)} className="rounded bg-blue-600 px-4 py-2 text-white">Add contact</button><a className="rounded border px-4 py-2" href={`/api/crm/workspaces/${workspaceId}/contacts/export?format=csv`}>Export CSV</a></div><div className={base}><table className="w-full text-left"><thead><tr className="border-b text-slate-500"><th className="p-2">Name</th><th>Email</th><th>Phone</th><th>Tags</th></tr></thead><tbody>{contacts.map(c => <tr className="border-b" key={c.id}><td className="p-2"><Link className="text-blue-600" to={`/crm/contacts/${c.id}?workspace=${workspaceId}`}>{c.firstName} {c.lastName}</Link></td><td>{c.email || '—'}</td><td>{c.phone || '—'}</td><td>{c.tags.map(x => <span key={x.tag.id} style={{ backgroundColor: x.tag.color }} className="mr-1 rounded px-2 py-1 text-xs text-white">{x.tag.name}</span>)}</td></tr>)}</tbody></table></div></section>}
    {tab === 'pipeline' && <section><div className="mb-4"><button onClick={() => setShowPipeline(true)} className="rounded bg-blue-600 px-4 py-2 text-white">Create pipeline</button></div>{pipelines.map(p => <div key={p.id} className="mb-6"><h2 className="mb-3 text-xl font-bold">{p.name}</h2><div className="grid min-w-max grid-flow-col auto-cols-[250px] gap-4 overflow-x-auto">{p.stages.map(stage => <div key={stage.id} onDragOver={e => e.preventDefault()} onDrop={e => moveOpportunity(e.dataTransfer.getData('opportunity'), stage.id)} className="rounded-lg bg-slate-200 p-3"><h3 className="mb-3 font-semibold">{stage.name} <span className="text-slate-500">{stage.opportunities.length}</span></h3>{stage.opportunities.map(o => <div draggable onDragStart={e => e.dataTransfer.setData('opportunity', o.id)} key={o.id} className="mb-2 cursor-grab rounded bg-white p-3 shadow"><p className="font-medium">{o.title}</p><p className="text-sm text-slate-600">{o.contact.firstName} {o.contact.lastName}</p><p className="text-sm">{o.dealValue ? `$${o.dealValue}` : 'No value'}</p></div>)}</div>)}</div></div>)}</section>}
    {tab === 'settings' && <section className="grid gap-6 md:grid-cols-2"><div className={base}><h2 className="mb-3 text-xl font-bold">Tags</h2><form onSubmit={addTag} className="mb-4 flex gap-2"><input name="name" required placeholder="Tag name" className="min-w-0 flex-1 rounded border p-2"/><input name="color" type="color" defaultValue="#3B82F6"/><button className="rounded bg-blue-600 px-3 text-white">Add</button></form>{tags.map(t => <span key={t.id} style={{ backgroundColor: t.color }} className="mr-2 inline-block rounded px-2 py-1 text-white">{t.name}</span>)}</div><div className={base}><h2 className="mb-3 text-xl font-bold">Custom fields</h2><form onSubmit={addField} className="mb-4 flex flex-wrap gap-2"><input name="name" required placeholder="Field name" className="rounded border p-2"/><select name="fieldType" className="rounded border p-2">{['text','number','date','dropdown','checkbox','phone','email'].map(t => <option key={t}>{t}</option>)}</select><label className="p-2 text-sm"><input name="isRequired" type="checkbox"/> Required</label><button className="rounded bg-blue-600 px-3 text-white">Add</button></form>{fields.map(f => <p key={f.id} className="border-t py-2">{f.name} <span className="text-sm text-slate-500">{f.fieldType}</span></p>)}</div></section>}
    {showContact && <div className="fixed inset-0 grid place-items-center bg-black/40 p-4"><form onSubmit={createContact} className="w-full max-w-md rounded bg-white p-6"><h2 className="mb-4 text-xl font-bold">New contact</h2><div className="grid gap-3"><input name="firstName" required placeholder="First name" className="rounded border p-2"/><input name="lastName" required placeholder="Last name" className="rounded border p-2"/><input name="email" type="email" placeholder="Email" className="rounded border p-2"/><input name="phone" placeholder="Phone" className="rounded border p-2"/><input name="source" placeholder="Source" className="rounded border p-2"/><select name="tagIds" multiple className="rounded border p-2">{tags.map(t => <option value={t.id} key={t.id}>{t.name}</option>)}</select><div className="flex justify-end gap-2"><button type="button" onClick={() => setShowContact(false)} className="rounded border px-3 py-2">Cancel</button><button className="rounded bg-blue-600 px-3 py-2 text-white">Create</button></div></div></form></div>}
    {showPipeline && <div className="fixed inset-0 grid place-items-center bg-black/40 p-4"><form onSubmit={createPipeline} className="w-full max-w-md rounded bg-white p-6"><h2 className="mb-4 text-xl font-bold">New pipeline</h2><div className="grid gap-3"><input name="name" required placeholder="Pipeline name" className="rounded border p-2"/><textarea name="description" placeholder="Description" className="rounded border p-2"/><p className="text-sm text-slate-500">Creates: New Lead, Contacted, Qualified, Proposal, Won, Lost.</p><div className="flex justify-end gap-2"><button type="button" onClick={() => setShowPipeline(false)} className="rounded border px-3 py-2">Cancel</button><button className="rounded bg-blue-600 px-3 py-2 text-white">Create</button></div></div></form></div>}
  </div></main>;
}
